export const tasks = [
         {
        id: 1,
        heading: 'Learn react qwqwqwqwqw qw qwqwqwqwqwq  qwqwqwqwqw',
        description: 'Be the best at react.',
        dateTime : new Date(Date.now()),
        image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
         priority: 'low',  
      },
        {
          id: 2,
          heading: "Master Javascript",
          description: "Unlock the power of the web",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'low',  
        },
        {
          id: 3,
          heading: "Build Scalable APIs",
          description: "Connect your applications seamlessly",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'medium',  
          },
        {
          id: 4,
          heading: "Dive into Data Science",
          description: "Uncover insights from your data",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'medium',  
          },
        {
          id: 5,
          heading: "Learn Version Control",
          description: "Collaborate effectively with Git",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'medium',  
          },
        {
          id: 6,
          heading: "Become a UI/UX Designer",
          description: "Craft beautiful and user-friendly interfaces",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'medium',  
        },
        {
          id: 7,
          heading: "Master SEO Strategies",
          description: "Improve your website's ranking",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'medium',  
      
        },
        {
          id: 8,
          heading: "Build Responsive Websites",
          description: "Make your website adapt to any device",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'high',  
        },
        {
          id: 9,
          heading: "Explore Cloud Computing",
          description: "Scale your applications with ease",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'high',  
          },
        {
          id: 10,
          heading: "Learn Cybersecurity Essentials",
          description: "Protect your data from cyber threats",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'high',  
          },
        {
          id: 11,
          heading: "Become a Data Analyst",
          description: "Clean, analyze, and visualize data",
          dateTime: new Date(Date.now()),
          image: 'https://res.cloudinary.com/dxv2tmvfw/image/upload/v1715862148/pigeons/app/testImage_zu8yp3.jpg',
          priority: 'high',  
        }
      ]
      
